# 01:createkn01.java
# all:
# 	javac createkn01.java
# 	java createkn01 knapsack01.txt

# 02:bruteforce.java
# all:
# 	javac bruteforce.java
# 	java bruteforce knapsack01.txt

# #03:dynpro.java
# all:
# 	javac dynpro.java
# 	java dynpro knapsack01.txt

# #04:igreedy.java
# all:
# 	javac igreedy.java
# 	java igreedy knapsack01.txt
